image: edbizarro/gitlab-ci-pipeline-php:7.2

services:
  - mysql:5.6

variables:
  MYSQL_DATABASE: vodafone_test
  MYSQL_USER: vodafone
  MYSQL_PASSWORD: vodafone123
  MYSQL_ROOT_PASSWORD: secret

stages:
  - test
#  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - sources/vendor/

before_script:
  - php sources/init.php --env=Test --overwrite=y
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --working-dir=sources

test:
  stage: test
  only:
    refs:
      - develop
      - master
      - staging
      - live
  script:
    - echo "Test - start"
    - php sources/bin/console doctrine:migrations:migrate --env="test"
    - php sources/bin/console doctrine:fixtures:load -n
    - php sources/vendor/bin/php-cs-fixer fix --dry-run --diff --config='sources/.php_cs'
#    - php sources/vendor/bin/phpstan analyse --no-progress -l 6 -c sources/phpstan.neon sources/src
    - php sources/bin/phpunit --configuration sources/phpunit.xml.dist
    - echo "Test - finish"
