image: edbizarro/gitlab-ci-pipeline-php:7.3

services:
  - postgres:11

variables:
  POSTGRES_DB: test
  POSTGRES_USER: api_boilerplate
  POSTGRES_PASSWORD: api_boilerplate123

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - sources/vendor/

before_script:
  - php sources/init.php --env=Test --overwrite=y
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --working-dir=sources

test:
  stage: test
  only:
    refs:
      - develop
      - master
      - staging
      - live
  script:
    - echo "Test - start"
    - php sources/bin/console doctrine:migrations:migrate --env="test"
    - php sources/bin/console doctrine:fixtures:load -n
    - php sources/vendor/bin/php-cs-fixer fix --dry-run --diff --config='sources/.php_cs'
    - php sources/vendor/bin/phpstan analyse --no-progress -l 4 -c sources/phpstan.neon sources/src
    - php sources/bin/phpunit --configuration sources/phpunit.xml.dist
    - echo "Test - finish"
