services:
    admin.users:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "Users" }
        calls:
            - [setUserManager, ['@App\Service\UserManager']]

