services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Documentation\Paths\:
        public: true
        resource: '../../src/Documentation/Paths'
        tags:
            - { name: documentation.paths }

    App\Documentation\Components\Schemas\:
        public: true
        resource: '../../src/Documentation/Components/Schemas'
        tags:
            - { name: documentation.schemas }

    App\Documentation\Components\UpdatableSchemas\:
        public: true
        resource: '../../src/Documentation/Components/UpdatableSchemas'
        tags:
            - { name: documentation.updatable_schemas }

    App\Documentation\DocumentationNormalizer:
        decorates: api_platform.swagger.normalizer.api_gateway
        arguments: ['@App\Documentation\DocumentationNormalizer.inner']
        calls:
            - [setPaths, [!tagged documentation.paths]]
            - [setUpdatableSchemas, [!tagged documentation.updatable_schemas]]
            - [setSchemas, [!tagged documentation.schemas]]
            - [setHiddenPaths, [[]]]
#            - [setHiddenPaths, [['Some route', 'Another route']]]
