#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'admin_login'

sonata_admin_dashboard:
    path: /admin/dashboard
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'admin_app_user_list'

swagger_ui:
    path: /api/doc
    controller: api_platform.swagger.action.ui

api_login_check:
    path: /api/login-check
